#!/usr/local/bin/bash
#set -x

BACKUP="/backup"
HASHDIR="/export/hashdeep"
# Ubuntu hashdeep TESTED OK
#HASHDEEP="/usr/bin/hashdeep"
# FreeBSD md5deep TESTED OK
HASHDEEP="/usr/local/bin/md5deep"
# Ubuntu hasdeep configuration
# HASHDEEPCONF="-w -o f -l -r -x -k"
# FreeBSD md5deep configuration
HASHDEEPCONF="-w -o f -l -r -x"

USAGE="$(basename "$0") [-h|--help] [-l|--list] [-s|--silent] [-a|--all|<client>] -- check integrity
where:
    -h --help             show this help text
    -s --silent           report errors only
    -l --list             list clients
    -a --all              check integrity of all clients
    <client>              check integrity of client"

EXPECTED_ARGS=1
if [ $# -lt $EXPECTED_ARGS ]; then
    echo "$USAGE"
    exit
fi

# Command to create the hash-files (both FreeBSD and Ubuntu tested OK)
# cd $BACKUP; $HASHDEEP -e -o f -l -r $CLIENT > $HASHDIR/$CLIENT.hashdeep
function check-integrity {
# Files not included in hash-files will be printed (VERBOSE only)
# Changed files  in the has-files will be printed (hash error)
	 (($VERBOSE)) && printf "*** intergrity of $CLIENT ---------------------------------------\n"
	 if LOG=$(cd $BACKUP; $HASHDEEP $HASHDEEPCONF $HASHDIR/$CLIENT.hashdeep $CLIENT 2>&1); then
	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT hash correct\n"
	     (($VERBOSE)) && printf "$LOG\n"
	 else
	     printf "[ERR] integrity: $CLIENT hash error $?\n"
	     printf "$LOG\n"
	 fi
}

VERBOSE=1
CLIENTS=$(cd $HASHDIR;ls -1 *.hashdeep | rev | cut -d'.' -f2- | rev)
for i in "$@"; do
    case $i in
	-h|--help)
	    echo "$USAGE"
	    exit
	    ;;
	-l|--list)
	    printf "$CLIENTS\n"
	    ;;
	-s|--silent)
	    VERBOSE=0
	    ;;
	-a|--all)
	    for CLIENT in $CLIENTS; do
		check-integrity
	    done
	    ;;
	*)
	    if [[ $CLIENTS =~ $i ]] ; then
		CLIENT=$i
		check-integrity
	    else
		printf "[ERR] integrity: Unknown client $i\n"
	    fi
	    ;;
    esac
done

exit
