#!/usr/local/bin/bash
#set -x

# Ubuntu configuration
# HASHDEEP="/usr/bin/hashdeep"
# HASHDEEPCONF="-w -o f -l -r -x -k"
# MTREE="/usr/bin/fmtree"

# FreeBSD configration
HASHDEEP="/usr/local/bin/md5deep"
HASHDEEPCONF="-w -o f -l -r -x"
MTREE="/usr/sbin/mtree"

# General configuration
BACKUP="/integrity"
HASHDIR="/hashdeep"
# default set of keywords are flags, gid, link, mode, nlink, size, time, and uid
MTREEKEYS="-k gid,link,mode,nlink,size,time,uid"
[ -f /etc/integrity ] && . /etc/integrity
[ -f ~/.integrity ] && . ~/.integrity

USAGE="$(basename "$0") [-h|--help] [-s|--silent] [-c|--commands] [-r|--recreate] [-l|--list]
          [-a|--all|<client>] -- check integrity
where:
    -h --help             show this help
    -s --silent           report errors only
    -c --commands         list commands to create the hash and mtree files
    -r --recreate         recreate the hash and mtree files of all clients
    -l --list             list clients
    -a --all              check integrity of all clients
    <client>              check integrity of client"

EXPECTED_ARGS=1
if [ $# -lt $EXPECTED_ARGS ]; then
    echo "$USAGE"
    exit
fi

function check-integrity {
# Files not included in hash-files will be printed (VERBOSE only)
# Changed files in the hash-files will be printed (hash error)
	 (($VERBOSE)) && printf "[OK] integrity: *** $CLIENT check started\n"
	 if LOG=$(cd $BACKUP; $HASHDEEP $HASHDEEPCONF $HASHDIR/$CLIENT.hashdeep $CLIENT/ 2>&1); then
	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT hash correct\n"
	     (($VERBOSE)) && [[ ! -z $LOG ]] && printf "[OK] integrity: hashdeep: $LOG\n"
	 else
	     printf "[ERR] integrity: $CLIENT hash error $?\n"
	     printf "[ERR] integrity: hashdeep: $LOG\n"
	 fi
	 if LOG=$(cd $BACKUP; $MTREE -f $HASHDIR/$CLIENT.mtree -p $CLIENT/ 2>&1); then
	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT mtree correct\n"
	     (($VERBOSE)) && [[ ! -z $LOG ]] && printf "[OK] integrity: mtree: $LOG\n"
	 else
	     printf "[ERR] integrity: $CLIENT mtree error $?\n"
	     printf "[ERR] integrity: mtree: $LOG\n"
	 fi
}

VERBOSE=1
CLIENTS=$(cd $HASHDIR;ls -1 *.hashdeep | rev | cut -d'.' -f2- | rev)
for i in "$@"; do
    case $i in
	-h|--help)
	    echo "$USAGE"
	    exit
	    ;;
	-l|--list)
	    printf "$CLIENTS\n"
	    exit
	    ;;
	-c|--commands)
	    printf "Commands to create the hash adn mtree files:\n"
	    for i in $CLIENTS; do
		printf "cd $BACKUP; $HASHDEEP -e -o f -l -r $i/ > $HASHDIR/$i.hashdeep\n"
		printf "cd $BACKUP; $MTREE -c -p $i/ > $HASHDIR/$i.mtree\n"
		printf "\n"
	    done
	    exit
	    ;;
	-r|--recreate)
	    for i in $CLIENTS; do
		(($VERBOSE)) && printf "[OK] integrity: Recreating $HASHDIR/$i.hashdeep started\n"
		cd $BACKUP; $HASHDEEP -e -o f -l -r $i/ > $HASHDIR/$i.hashdeep
		(($VERBOSE)) && printf "[OK] integrity: Recreating $HASHDIR/$i.hashdeep finished\n"
		(($VERBOSE)) && printf "[OK] integrity: Recreating $HASHDIR/$i.mtree started\n"
		cd $BACKUP; $MTREE $MTREEKEYS -c -p $i/ > $HASHDIR/$i.mtree
		(($VERBOSE)) && printf "[OK] integrity: Recreating $HASHDIR/$i.mtree finished\n"
	    done
	    exit
	    ;;
	-s|--silent)
	    VERBOSE=0
	    ;;
	-a|--all)
	    for CLIENT in $CLIENTS; do
		check-integrity
	    done
	    ;;
	*)
	    if [[ $CLIENTS =~ $i ]] ; then
		CLIENT=$i
		check-integrity
	    else
		printf "[ERR] integrity: Unknown client $i\n"
	    fi
	    ;;
    esac
done

exit
