---

rcb_bck_shell: /bin/bash

rcb_bck_dst: /scratch/rcb
rcb_root_public_keys_dir: /tmp

# rcb_bck_user: rcbackup
# rcb_bck_group: rcbackup
# The config parameter BCK_DST will be replaced by rcb_BCK_DST/ansible_hostname
