---

rcb_BCK_HOST: "backup.example.org"
rcb_BCK_DST: "/scratch/rcb"

#
# source
rcb_source_version: "0.2.0"
rcb_source_file: "{{rcb_source_version}}.tar.gz"
rcb_source_dir: "rcb-{{rcb_source_version}}"
rcb_source_dest: "/usr/local/src"
rcb_source_url: "https://github.com/vbotka/rcb/archive"

# directories
rcb_bin_dir: "/root/bin"
rcb_etc_dir: "/usr/local/etc"
rcb_snapshot_root: "/scratch/rcb/backup/snapshots"
rcb_test_dir: "/scratch/rcb/test"

# files
rcb_rcb_conf: "rcb.conf"
rcb_rsnapshot_conf: "rsnapshot.conf"

# CN
rcb_cert_CN: "example.com"

# rcb.conf
#
# RCB_HOST will be replaced with ansible_hostname
rcb_RCB_EMAIL: "root"
rcb_RCB_BCK_ROOT: "/scratch/rcb/backup"
rcb_RCB_BCK_PREFIX: "snapshots/hourly.0"
# path length of $RCB_BCK_ROOT/$RCB_BCK_PREFIX
rcb_RSYNCRYPTO_TRIM_E: "5"
# path length of $RCB_BCK_ROOT/enc
rcb_RSYNCRYPTO_TRIM_D: "4"
rcb_RCB_RST_ROOT: "/scratch/rcb/restore"
rcb_RCB_CRT_ROOT: "/scratch/rcb/cert"

# backup server
#rcb_BCK_HOST: "FQN-OF-BACKUP-SERVER"
rcb_BCK_USER: "rcbackup"
rcb_BCK_GROUP: "rcbackup"
# rcb_BCK_DST: "/scratch/rcb"
# BCK_DST will be replaced with rcb_BCK_DST/ansible_hostname


# EOF
...
