---

rcb_bck_host: backup.example.org
rcb_bck_dst: /scratch/rcb

# certificate
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# rcb_cert_cn: myhostname.example.com
# rcb_privatekey_passphrase: passphrase

# source
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# rcb_source_version: 1.1.0
# rcb_source_checksum: 'sha256:04724edd070018978c918ff4f4f18f710b383620ff2ec63fdbcb621eea921bbb'
# rcb_source_file: "{{rcb_source_version}}.tar.gz"
# rcb_source_dir: "rcb-{{rcb_source_version}}"
# rcb_source_dest: /usr/local/src
# rcb_source_url: https://github.com/vbotka/rcb/archive

# directories
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# rcb_bin_dir: /root/bin
# rcb_etc_dir: /usr/local/etc
# rcb_snapshot_root: /scratch/rcb/backup/snapshots

# conf
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# rcb_rcb_conf: rcb.conf
# rcb_rsnapshot_conf: rsnapshot.conf

# rcb.conf
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Config parameter RCB_HOST will be replaced by ansible_hostname
# rcb_rcb_email: root
# rcb_rcb_bck_root: /scratch/rcb/backup
# rcb_rcb_bck_prefix: snapshots/hourly.0
# path length of $RCB_BCK_ROOT/$RCB_BCK_PREFIX
# rcb_rsyncrypto_trim_e: 5
# path length of $RCB_BCK_ROOT/enc
# rcb_rsyncrypto_trim_d: 4
# rcb_rcb_rst_root: /scratch/rcb/restore
# rcb_rcb_crt_root: /scratch/rcb/cert

# backup server
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# rcb_bck_host: 'FQN-OF-BACKUP-SERVER'
# rcb_bck_user: rcbackup
# rcb_bck_group: rcbackup
# rcb_bck_dst: /scratch/rcb
# Config parameter BCK_DST will be replaced by rcb_BCK_DST/ansible_hostname


# EOF
...
