---

- hosts: rcb_server
  become: true
  become_user: root
  become_method: sudo

  vars:

    rcb_root_public_keys_dir: copy/rcb-root-ssh-pub-keys
    rcb_bck_dst: /export/rcbackup
    rcb_bck_dst_test: /export/rcbackup-test
    rcb_bck_user: rcbackup
    rcb_bck_group: rcbackup
    rcb_bck_shell: /usr/local/bin/bash

  tasks:

    - name: "Create user {{ rcb_bck_user }}"
      ansible.builtin.user:
        name: "{{ rcb_bck_user }}"
        shell: "{{ rcb_bck_shell }}"
      register: rcbuser

    - name: "Create directories"
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: "{{ rcb_bck_user }}"
        group: "{{ rcb_bck_group }}"
        mode: '0700'
      loop:
        - "{{ rcb_bck_dst }}"
        - "{{ rcb_bck_dst_test }}"

    - name: "Debug Public keys"
      ansible.builtin.debug:
        msg: "Public key {{ item }}"
      with_fileglob: "{{ rcb_root_public_keys_dir }}/{{ inventory_hostname }}/*.id_rsa.pub"
      loop_control:
        label: "{{ item|basename }}"
      when: debug|d(false)|bool

    - name: "Set up authorized_keys for {{ rcb_bck_user }}
             to {{ rcb_root_public_keys_dir }}/{{ inventory_hostname }}"
      ansible.posix.authorized_key:
        user: "{{ rcb_bck_user }}"
        key: "{{ lookup('file', '{{ item }}')}}"
      with_fileglob: "{{ rcb_root_public_keys_dir }}/{{ inventory_hostname }}/*.id_rsa.pub"
      loop_control:
        label: "{{ item|basename }}"

# EOF
...
