---

- hosts: rcb-devel
  become: yes
  become_method: sudo

  vars:
    bin_dir: "/root/bin"
    bin_items: {}
    source_path: "/scratch/rcb/" # If rcb is a symbolic link trailing slash is needed
    source_dest: "/usr/local/src/rcb-current"
    source_link: "/usr/local/src/rcb"
    source_lock: "/usr/local/src/rcb-current.lock"
    source_lock_set: "yes"


  tasks:

    - name: Install rsync (FreeBSD)
      pkgng: name="{{item}}" state="present"
      with_items:
        - rsync
      when: ansible_os_family == "FreeBSD"

    - name: Install rsync (Debian)
      apt: name="{{item}}" state="present"
      with_items:
       - rsync
      when: ansible_os_family == "Debian"

    - name: Install rsync (RedHat)
      yum: name="{{item}}" state="present"
      with_items:
        - rsync
      when: ansible_os_family == "RedHat"

    - name: Copy current source to {{ source_dest }}
      synchronize:
        src: "{{ source_path }}"
        dest: "{{ source_dest }}"
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"

    - name: Create symbolic link to {{ source_dest }}
      file: >
        src="{{ source_dest }}"
        dest="{{ source_link }}"
        state="link"
        force="yes"

    - name: Lock development version
      command: "touch {{ source_lock }}"
      args:
        creates: "{{ source_lock }}"
        warn: False 
      when: source_lock_set == "yes"
# Ignore warning. Module file does not work as described.
#     file: >
#       path="{{ source_lock }}"
#       state="touch"

    - name: Unlock development version
      command: "rm {{ source_lock }}"
      args:
        removes: "{{ source_lock }}"
        warn: False 
      when: source_lock_set == "no"
# Ignore warning. Module file does not work as described.
#     file: >
#       path="{{ source_lock }}"
#       state="absent"

# EOF
...
