---

- hosts: rcb_clients
  become: true
  become_user: root
  become_method: sudo

  vars_files:
    - rcb_privatekey_passphrase.yml

  vars:

    rcb_bck_host: 10.1.0.10
    rcb_bck_dst: /export/rcbackup
    rcb_root_public_keys_dir: copy/rcb-root-ssh-pub-keys
    rcb_rcb_bck_root: /export/backup
    rcb_rcb_rst_root: /export/restore
    rcb_rcb_crt_root: /root/rcb/cert
    rcb_cert_cn: rcb_client_01.example.org

  roles:
    - vbotka.rcb

# EOF
...
